import React, { useState } from 'react'

import PropTypes from 'prop-types'

import './pricing14.css'

const Pricing14 = (props) => {
  const [isMonthly, setIsMonthly] = useState(true)
  return <div className="pricing14-pricing23 thq-section-padding"></div>
}

Pricing14.defaultProps = {
  plan3Feature21: 'Feature text goes here',
  plan1Feature11: 'Real-time monitoring and analytics',
  plan3Feature51: 'Feature text goes here',
  content1: 'Choose the perfect plan for you',
  plan3Feature31: 'Feature text goes here',
  plan3Feature1: 'Feature text goes here',
  heading1: 'Pricing plan',
  plan2Feature4: 'Feature text goes here',
  plan3Feature3: 'Feature text goes here',
  plan3Yearly1: 'or $49 monthly',
  plan1Feature2: 'Energy efficiency optimization',
  plan2Price1: '$299/yr',
  plan2Feature31: 'Feature text goes here',
  plan3Price1: '$499/yr',
  plan2Feature2: 'Feature text goes here',
  plan1Yearly: '$1000/year',
  plan3Feature4: 'Feature text goes here',
  plan3Action1: 'Get started',
  plan11: 'Basic plan',
  plan3Feature11: 'Feature text goes here',
  plan1Action1: 'Get started',
  plan3Yearly: 'or $499 yearly',
  plan1Feature1: 'Decentralized control of street lighting',
  plan3Action: 'Get started',
  plan2Action1: 'Get started',
  plan3: 'Enterprise plan',
  plan21: 'Business plan',
  plan3Feature41: 'Feature text goes here',
  plan2Feature3: 'Feature text goes here',
  plan2Feature21: 'Feature text goes here',
  plan2Feature11: 'Feature text goes here',
  plan1Price: '$100/month',
  plan1Price1: '$200/yr',
  plan3Feature2: 'Feature text goes here',
  plan2Feature41: 'Feature text goes here',
  plan1: 'Basic Plan',
  plan1Action: 'Sign Up Now',
  plan1Feature3: 'Operational cost reduction',
  plan1Yearly1: 'or $20 monthly',
  content2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
  plan2Yearly: 'or $299 yearly',
  plan1Feature31: 'Customizable scheduling options',
  plan2Price: '$29/mo',
  plan1Feature21: 'Automatic fault detection and reporting',
  plan2Yearly1: 'or $29 monthly',
  plan31: 'Enterprise plan',
  plan2Feature1: 'Feature text goes here',
  plan3Feature5: 'Feature text goes here',
  plan2: 'Business plan',
  plan2Action: 'Get started',
  plan3Price: '$49/mo',
}

Pricing14.propTypes = {
  plan3Feature21: PropTypes.string,
  plan1Feature11: PropTypes.string,
  plan3Feature51: PropTypes.string,
  content1: PropTypes.string,
  plan3Feature31: PropTypes.string,
  plan3Feature1: PropTypes.string,
  heading1: PropTypes.string,
  plan2Feature4: PropTypes.string,
  plan3Feature3: PropTypes.string,
  plan3Yearly1: PropTypes.string,
  plan1Feature2: PropTypes.string,
  plan2Price1: PropTypes.string,
  plan2Feature31: PropTypes.string,
  plan3Price1: PropTypes.string,
  plan2Feature2: PropTypes.string,
  plan1Yearly: PropTypes.string,
  plan3Feature4: PropTypes.string,
  plan3Action1: PropTypes.string,
  plan11: PropTypes.string,
  plan3Feature11: PropTypes.string,
  plan1Action1: PropTypes.string,
  plan3Yearly: PropTypes.string,
  plan1Feature1: PropTypes.string,
  plan3Action: PropTypes.string,
  plan2Action1: PropTypes.string,
  plan3: PropTypes.string,
  plan21: PropTypes.string,
  plan3Feature41: PropTypes.string,
  plan2Feature3: PropTypes.string,
  plan2Feature21: PropTypes.string,
  plan2Feature11: PropTypes.string,
  plan1Price: PropTypes.string,
  plan1Price1: PropTypes.string,
  plan3Feature2: PropTypes.string,
  plan2Feature41: PropTypes.string,
  plan1: PropTypes.string,
  plan1Action: PropTypes.string,
  plan1Feature3: PropTypes.string,
  plan1Yearly1: PropTypes.string,
  content2: PropTypes.string,
  plan2Yearly: PropTypes.string,
  plan1Feature31: PropTypes.string,
  plan2Price: PropTypes.string,
  plan1Feature21: PropTypes.string,
  plan2Yearly1: PropTypes.string,
  plan31: PropTypes.string,
  plan2Feature1: PropTypes.string,
  plan3Feature5: PropTypes.string,
  plan2: PropTypes.string,
  plan2Action: PropTypes.string,
  plan3Price: PropTypes.string,
}

export default Pricing14
